// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Swagger Simple Petstore
This is a simplified version of the sample server Petstore server.


    Schemes:
      http
    Host: localhost:5000
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
