// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/Stratoscale/swagger/example/models"
)

/*PetUpdateParams contains all the parameters to send to the API endpoint
for the pet update operation typically these are written to a http.Request
*/
type PetUpdateParams struct {

	/*Body
	  Pet object that needs to be added to the store

	*/
	Body *models.Pet

	Timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *PetUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.Timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
