// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/Stratoscale/swagger/example/models"
)

// NewPetUpdateParams creates a new PetUpdateParams object
// with the default values initialized.
func NewPetUpdateParams() *PetUpdateParams {
	var ()
	return &PetUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPetUpdateParamsWithTimeout creates a new PetUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPetUpdateParamsWithTimeout(timeout time.Duration) *PetUpdateParams {
	var ()
	return &PetUpdateParams{

		timeout: timeout,
	}
}

// NewPetUpdateParamsWithContext creates a new PetUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPetUpdateParamsWithContext(ctx context.Context) *PetUpdateParams {
	var ()
	return &PetUpdateParams{

		Context: ctx,
	}
}

// NewPetUpdateParamsWithHTTPClient creates a new PetUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPetUpdateParamsWithHTTPClient(client *http.Client) *PetUpdateParams {
	var ()
	return &PetUpdateParams{
		HTTPClient: client,
	}
}

/*PetUpdateParams contains all the parameters to send to the API endpoint
for the pet update operation typically these are written to a http.Request
*/
type PetUpdateParams struct {

	/*Pet
	  Pet object that needs to be added to the store

	*/
	Pet *models.Pet
	/*PetID
	  ID of pet to return

	*/
	PetID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pet update params
func (o *PetUpdateParams) WithTimeout(timeout time.Duration) *PetUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pet update params
func (o *PetUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pet update params
func (o *PetUpdateParams) WithContext(ctx context.Context) *PetUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pet update params
func (o *PetUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pet update params
func (o *PetUpdateParams) WithHTTPClient(client *http.Client) *PetUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pet update params
func (o *PetUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPet adds the pet to the pet update params
func (o *PetUpdateParams) WithPet(pet *models.Pet) *PetUpdateParams {
	o.SetPet(pet)
	return o
}

// SetPet adds the pet to the pet update params
func (o *PetUpdateParams) SetPet(pet *models.Pet) {
	o.Pet = pet
}

// WithPetID adds the petID to the pet update params
func (o *PetUpdateParams) WithPetID(petID int64) *PetUpdateParams {
	o.SetPetID(petID)
	return o
}

// SetPetID adds the petId to the pet update params
func (o *PetUpdateParams) SetPetID(petID int64) {
	o.PetID = petID
}

// WriteToRequest writes these params to a swagger request
func (o *PetUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Pet != nil {
		if err := r.SetBodyParam(o.Pet); err != nil {
			return err
		}
	}

	// path param petId
	if err := r.SetPathParam("petId", swag.FormatInt64(o.PetID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
